# Generated by Django 2.1.1 on 2018-10-14 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closeknit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friend',
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, to='closeknit.User'),
        ),
    ]
