# Generated by Django 2.1.1 on 2018-10-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closeknit', '0007_auto_20181014_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, default=None, limit_choices_to={'username != __str__': True}, related_name='_user_friends_+', to='closeknit.User'),
        ),
    ]
