# Generated by Django 2.1.1 on 2018-10-18 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closeknit', '0010_auto_20181018_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_stamp',
            field=models.DateTimeField(default=1991),
        ),
    ]
