# Generated by Django 2.1.1 on 2018-10-18 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closeknit', '0015_auto_20181018_0303'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reacts',
            new_name='Comment',
        ),
    ]
