# Generated by Django 2.1.1 on 2018-10-18 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('closeknit', '0018_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='closeknit.Post'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='closeknit.User'),
        ),
    ]
