# Generated by Django 2.1.1 on 2018-10-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closeknit', '0024_remove_post_img_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_content',
            field=models.ImageField(default='SOME_IMG', upload_to=None),
        ),
    ]
