# Generated by Django 2.1.1 on 2018-10-18 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('closeknit', '0009_auto_20181014_0454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=250)),
                ('time_stamp', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='img_content',
            field=models.ImageField(default='SOME_IMG', upload_to=None),
        ),
        migrations.AddField(
            model_name='post',
            name='text_content',
            field=models.TextField(default='SOME_TEXT', help_text='Whats on your mind?', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='time_stamp',
            field=models.DateTimeField(default='2018-10-17T23:02:30Z'),
        ),
        migrations.AddField(
            model_name='reacts',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='closeknit.Post'),
        ),
        migrations.AddField(
            model_name='reacts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='closeknit.User'),
        ),
    ]
