# Generated by Django 2.1.1 on 2018-10-18 02:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closeknit', '0013_auto_20181018_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_stamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='reacts',
            name='time_stamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
