# Generated by Django 2.1.1 on 2018-10-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closeknit', '0008_auto_20181014_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, default=None, related_name='_user_friends_+', to='closeknit.User'),
        ),
    ]
