# Generated by Django 2.1.1 on 2018-10-18 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closeknit', '0014_auto_20181018_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_stamp',
            field=models.DateTimeField(blank=True, default='2018-10-17T23:02:30Z'),
        ),
        migrations.AlterField(
            model_name='reacts',
            name='time_stamp',
            field=models.DateTimeField(blank=True, default='2018-10-17T23:02:30Z'),
        ),
    ]
