# Generated by Django 2.1.1 on 2018-10-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closeknit', '0016_auto_20181018_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='SOME_NAME', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='SOME_NAME', max_length=30),
        ),
    ]
